#!/usr/bin/python3

import sys

def factors(num):
    n = 2
    if num < 2:
        return
    while num % n:
        n = n + 1
        print(f"{num:.0f} = {num / n:.0f } * {n:.0f}")
if len(sys.argv) != 2:
    sys.exit("Usage: factors <file>")

try:
    with open(sys.argv[1]) as file:
        for line in file:
            num = int(line.strip())
            factors(num)
except FileNotFoundError:
    print(f"File '{sys.argv[1]}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")
